/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi_ecommerce;

import java.awt.Font;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Personal
 */
public class datatransaksi extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private Connection connection;
    private Object c;
    public void selectData() {
        try {
            Connection c = koneksi.getConnection();
        Statement stat = c.createStatement();
        String sql = "SELECT * FROM table_uas";
        ResultSet rs = stat.executeQuery(sql);

            //mengisi tabel dgn data hasil query
            while (rs.next()) {
                Object[] bioskop = new Object[6];
                bioskop[0] = rs.getString("Id");
                bioskop[1] = rs.getString("Member");
                bioskop[2] = rs.getString("Item");
                bioskop[3] = rs.getString("Harga");
                bioskop[4] = rs.getString("Bayar");
                bioskop[5] = rs.getString("Kembali");
                tableModel.addRow(bioskop);
            }
            rs.close();
            rs.close();
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
}
    private void table(){
        tableModel = new DefaultTableModel();
        JTableHeader header = Tabledata.getTableHeader();
        header.setFont(new Font("Tekton Pro", Font.BOLD, 18));
        Tabledata.setModel(tableModel);
        tableModel.addColumn("Id");
        tableModel.addColumn("Member");
        tableModel.addColumn("Item");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Bayar");
        tableModel.addColumn("Kembalian");
        
    }
    public datatransaksi() {
        initComponents();
        table();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabledata = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Pencarian = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Member", "Item", "Harga", "Bayar", "Kembalian"
            }
        ));
        jScrollPane1.setViewportView(Tabledata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 760, 490));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText(" Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 180, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 80, 40));

        Pencarian.setBackground(new java.awt.Color(204, 204, 204));
        Pencarian.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jPanel1.add(Pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 380, 40));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 80, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 90));

        jLabel2.setFont(new java.awt.Font("Tekton Pro", 1, 48)); // NOI18N
        jLabel2.setText("DATABASE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel3.setText("*data ini hanya milik admin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(827, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Ekspor File Ke Microsoft Excel
        FileWriter file;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("export_output/excel"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION){
            try{
                TableModel model = Tabledata.getModel();
                file = new FileWriter(new File(chooser.getSelectedFile() +".xls"));

                for(int i=0; i < model.getColumnCount(); i++){
                    file.write(model.getColumnName(i).toUpperCase() + "\t");
                }
                file.write("\n");
                for(int i=0; i < model.getRowCount(); i++){
                    for(int j=0; j < model.getRowCount(); j++){
                        file.write(model.getValueAt(i,j).toString() + "\t");
                    }
                    file.write("\n");
                }
                file.close();
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        try{
            String cari = Pencarian.getText();
            Connection c = koneksi.getConnection();
            String sql = "SELECT * FROM table_uas WHERE Id LIKE '%" +cari+ "%'"
            + "OR Member LIKE'%"+ cari+ "%'";

            Statement stat = c.createStatement();
            ResultSet rs = stat.executeQuery(sql);
                
                while (rs.next()){
                    Object[] bioskop = new Object[6];
                    bioskop[0] = rs.getString("Id");
                    bioskop[1] = rs.getString("Member");
                    bioskop[2] = rs.getString("Item");
                    bioskop[3] = rs.getString("Harga");
                    bioskop[4] = rs.getString("Bayar");
                    bioskop[5] = rs.getString("Kembali");
                    tableModel.addRow(bioskop);
                    
                }
                rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(datatransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Menghapus Satu Baris Atau Satu Kolom Yang Ada di Tabel
        try{
            int baris = Tabledata.getSelectedRow();
            baris = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data?", "Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION);
            if (baris == 0){
                String nomor = Tabledata.getValueAt(baris, 0).toString();
                String SQL = "DELETE FROM table_uas WHERE Id= '"+nomor+"'";
                java.sql.Connection c= (Connection)koneksi.getConnection();
                java.sql.PreparedStatement pst= c.prepareStatement(SQL);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Berhasil DIhapus");
            }else{
                JOptionPane.showMessageDialog(this, "Gagal DIhapus");
            }
        }catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        table();
        selectData();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datatransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datatransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pencarian;
    private javax.swing.JTable Tabledata;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
