/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi_ecommerce;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Personal
 */
public class transaksi extends javax.swing.JFrame {

     int harga1, harga2, harga3, harga4, harga5;
    int total, bayar, kembali;
    String Item, iniHarga,pilihan, displayNumber="";
    public transaksi() {
        initComponents();
        id_auto();
    }

    public void id_auto() {
    try {
        Connection c = koneksi.getConnection();
        Statement stat = c.createStatement();
        String sql = "select max(right(id,3)) as no from table_uas";
        ResultSet rs = stat.executeQuery(sql);

        if (rs.next()) {
            if (rs.getString("no") == null) {
                id.setText("ID001");
            } else {
                int set_id = Integer.parseInt(rs.getString("no")) + 1;
                String no = String.format("%03d", set_id);
                id.setText("ID" + no);
            }
        }
        
        rs.close();
    } catch (SQLException ex) {
        Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    
    public void transaksi(){
        StringBuffer item = new StringBuffer();

	if(item1.isSelected()) {
		item.append(item1.getText() + "\n");
                harga1 = 10000;
//                displayMenu.setText("hp1");
	}
	if(item2.isSelected()) {
		item.append(item2.getText() + "\n");
                harga2 = 20000;
//                displayMenu.setText("hp2");
	}
	if(item3.isSelected()) {
		item.append(item3.getText() + "\n");
                harga3 = 30000;
//                displayMenu.setText("hp3");
	}
        if(item4.isSelected()) {
		item.append(item4.getText() + "\n");
                harga4 = 40000;
//                displayMenu.setText("hp4");
	}
        if(item5.isSelected()) {
		item.append(item5.getText() + "\n");
                harga5 = 50000;
//                displayMenu.setText("hp5");
	}
            Item = item.toString();
            displayMenu.setText(Item);
            
            
    }
    
    public void member(){
        if (member.isSelected()){
            double a = (harga1 + harga2 + harga3 + harga4 + harga5)*0.5 ;
            displayHarga.setText(""+a);  
            pilihan = "member";
        }
        if (nonmember.isSelected()){
            int a = harga1 + harga2 + harga3 + harga4 + harga5;
            displayHarga.setText(""+a);  
            pilihan = "non member";
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        member = new javax.swing.JRadioButton();
        item1 = new javax.swing.JCheckBox();
        item2 = new javax.swing.JCheckBox();
        item4 = new javax.swing.JCheckBox();
        item3 = new javax.swing.JCheckBox();
        item5 = new javax.swing.JCheckBox();
        nonmember = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayMenu = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        displayHarga = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        displayKembali = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, 30));

        member.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(member);
        member.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        member.setText("Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        jPanel1.add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, -1));

        item1.setBackground(new java.awt.Color(255, 255, 255));
        item1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item1.setText("NIKE");
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });
        jPanel1.add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 20, -1));

        item2.setBackground(new java.awt.Color(255, 255, 255));
        item2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item2.setText("PUMA");
        item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ActionPerformed(evt);
            }
        });
        jPanel1.add(item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 20, -1));

        item4.setBackground(new java.awt.Color(255, 255, 255));
        item4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item4.setText("VANS");
        jPanel1.add(item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 20, -1));

        item3.setBackground(new java.awt.Color(255, 255, 255));
        item3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item3.setText("ADIDAS");
        jPanel1.add(item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 20, -1));

        item5.setBackground(new java.awt.Color(255, 255, 255));
        item5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item5.setText("CONVERSE");
        jPanel1.add(item5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 20, -1));

        nonmember.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(nonmember);
        nonmember.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nonmember.setText("Non Member");
        jPanel1.add(nonmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 80, -1));

        jButton1.setBackground(new java.awt.Color(255, 1, 1));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 80, -1));

        displayMenu.setEditable(false);
        displayMenu.setBackground(new java.awt.Color(255, 0, 0));
        displayMenu.setColumns(20);
        displayMenu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        displayMenu.setRows(5);
        jScrollPane1.setViewportView(displayMenu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 410, 130));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("*Sepatu yang  dipilih");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        displayHarga.setEditable(false);
        displayHarga.setBackground(new java.awt.Color(255, 0, 0));
        displayHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayHarga.setForeground(new java.awt.Color(255, 255, 255));
        displayHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        displayHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayHargaActionPerformed(evt);
            }
        });
        jPanel1.add(displayHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 410, 30));

        txtBayar.setBackground(new java.awt.Color(255, 0, 0));
        txtBayar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtBayar.setForeground(new java.awt.Color(255, 255, 255));
        txtBayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 410, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("*Total Bayar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, 20));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("*Kembalian");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, 20));

        displayKembali.setEditable(false);
        displayKembali.setBackground(new java.awt.Color(255, 2, 2));
        displayKembali.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayKembali.setForeground(new java.awt.Color(255, 255, 255));
        displayKembali.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(displayKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 410, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BAYAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 300, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/PMA.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/VANS.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 80, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/CNFRS.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 80, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/NIKE2.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 70, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/ADIDAS-.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 227, 90, 70));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 160));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("*Bayar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/promo-diskon-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -10, 370, 170));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaksi_ecommerce/akulaku1-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 260, 60));

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(616, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        transaksi();
     member();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    displayMenu.setText("");
    displayHarga.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        total  = (int) Double.parseDouble(displayHarga.getText());
        bayar = Integer.parseInt(txtBayar.getText());

        if (bayar<total){
            javax.swing.JOptionPane.showMessageDialog(null, "Maaf Uang Anda Kurang!");
            bayar=0;
            displayNumber="";
            txtBayar.setText("");
        }

        else {

            kembali = bayar - total;
            displayNumber = Integer.toString(kembali);
            displayKembali.setText(displayNumber);
            displayNumber = "";
            javax.swing.JOptionPane.showMessageDialog(null, "Pembayaran Anda Berhasil \n" + "Terima Kasih Sudah Belanja Di Sini \n" + "Silahkan Datang Kembali :)");

            try {

                String iniPilihan = pilihan;
                Connection connection = koneksi.getConnection();
                String query = "INSERT INTO table_uas (`Id`,`Member`, `Item`, `Harga`, `Bayar`, `Kembali`) VALUES (?,?,?,?,?,?)";
                java.sql.PreparedStatement statement = connection.prepareStatement(query);

                statement.setString(1, id.getText());
                statement.setString(2, iniPilihan);
                statement.setString(3, displayMenu.getText());
                statement.setString(4, displayHarga.getText());
                statement.setString(5, txtBayar.getText());
                statement.setString(6, displayKembali.getText());

                statement.executeUpdate();

                //            JOptionPane.showMessageDialog(null, "Input Succes");
                statement.close();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Input Failed!");
                System.out.println(ex);

            }
            datatransaksi dt = new datatransaksi();
            dt.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       txtBayar.setText("");
       displayKembali.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void displayHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayHargaActionPerformed

    private void item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item2ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField displayHarga;
    private javax.swing.JTextField displayKembali;
    private javax.swing.JTextArea displayMenu;
    private javax.swing.JTextField id;
    private javax.swing.JCheckBox item1;
    private javax.swing.JCheckBox item2;
    private javax.swing.JCheckBox item3;
    private javax.swing.JCheckBox item4;
    private javax.swing.JCheckBox item5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton member;
    private javax.swing.JRadioButton nonmember;
    private javax.swing.JTextField txtBayar;
    // End of variables declaration//GEN-END:variables
}
